MARKER_WIDTH = .1
LETTER_MATRIX_SIZE = 5
LETTER_SPACING = 2

LETTER_REF_FILE_PATH = "resources\Letter_Reference.xlsx"
OPTION_PRICE_DATA_PATH = "resources\CallPriceTemplate.xlsx"
OPTION_PRICE_DATA_TEMPLATE_SHEET_NAME = "Template"
OPTION_PRICE_DATA_META_SHEET_NAME = "Meta"
OPTION_PRICE_DATA_STRIKE_COLUMN_TITLE = "strike"
OPTION_PRICE_DATA_PRICE_COLUMN_TITLE = "price"

CALL_PRICE_PLOT_DENSITY = 1000
DERIVATIVE_PAYOFF_PLOT_DENSITY = 6000

CALL_PRICE_CHART_XLABEL = "Strike"
CALL_PRICE_CHART_YLABEL = "Approximated call price"

CALL_PRICE_TEMPLATE_UNDERLYING_PRICE_AT_SNAPSHOT_KEY = "Underlying price during call snapshot"